/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        }
      },
      fontFamily: {
        sans: ['system-ui', 'sans-serif'],
      },
      animation: {
        'bounce': 'bounce 1s infinite',
      },
      keyframes: {
        bounce: {
          '0%, 100%': {
            transform: 'translateY(-25%)',
            animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)',
          },
          '50%': {
            transform: 'none',
            animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
          },
        },
      },
    },
  },
  plugins: [],
  corePlugins: {
    // Disable unused features for smaller bundle
    preflight: true,
    container: false,
    accessibility: false,
    appearance: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundOrigin: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    filter: false,
    backdropFilter: false,
    borderCollapse: false,
    borderSpacing: false,
    tableLayout: false,
    captionSide: false,
    transitionProperty: false,
    transitionDuration: false,
    transitionTimingFunction: false,
    transitionDelay: false,
    animation: false,
    transform: false,
    transformOrigin: false,
    scale: false,
    rotate: false,
    translate: false,
    skew: false,
    transformStyle: false,
    perspective: false,
    perspectiveOrigin: false,
    backfaceVisibility: false,
    isolation: false,
    mixBlendMode: false,
    backgroundBlendMode: false,
    fill: false,
    stroke: false,
    strokeWidth: false,
    objectFit: false,
    objectPosition: false,
    overscrollBehavior: false,
    scrollSnapType: false,
    scrollSnapAlign: false,
    scrollSnapStop: false,
    scrollMargin: false,
    scrollPadding: false,
    listStyleImage: false,
    listStyleType: false,
    listStylePosition: false,
    placeholderColor: false,
    placeholderOpacity: false,
    caretColor: false,
    accentColor: false,
    scrollBehavior: false,
    touchAction: false,
    userSelect: false,
    resize: false,
    scrollSnapMargin: false,
    scrollSnapCoordinate: false,
    scrollSnapDestination: false,
    scrollSnapPointsX: false,
    scrollSnapPointsY: false,
    scrollSnapCoordinateX: false,
    scrollSnapCoordinateY: false,
    scrollSnapAlignX: false,
    scrollSnapAlignY: false,
    scrollSnapStopX: false,
    scrollSnapStopY: false,
    scrollSnapMarginTop: false,
    scrollSnapMarginRight: false,
    scrollSnapMarginBottom: false,
    scrollSnapMarginLeft: false,
    scrollSnapMarginX: false,
    scrollSnapMarginY: false,
    scrollSnapCoordinateTop: false,
    scrollSnapCoordinateRight: false,
    scrollSnapCoordinateBottom: false,
    scrollSnapCoordinateLeft: false,
    scrollSnapCoordinateX: false,
    scrollSnapCoordinateY: false,
    scrollSnapAlignTop: false,
    scrollSnapAlignRight: false,
    scrollSnapAlignBottom: false,
    scrollSnapAlignLeft: false,
    scrollSnapAlignX: false,
    scrollSnapAlignY: false,
    scrollSnapStopTop: false,
    scrollSnapStopRight: false,
    scrollSnapStopBottom: false,
    scrollSnapStopLeft: false,
    scrollSnapStopX: false,
    scrollSnapStopY: false,
  },
}; 