version: 0.2

env:
  image: aws/codebuild/amazonlinux-x86_64-standard:4.0-22.10.27

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1
      - docker login --username AWS --password-stdin 224776848598.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=224776848598.dkr.ecr.us-east-1.amazonaws.com/rant-zone-backend
      - IMAGE_TAG=latest

  build:
    commands:
      - echo "Building the Docker image..."
      - cd backend
      - docker build -f Dockerfile.aws -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"rant-zone-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: no

cache:
  paths:
    - '/root/.docker/**/*'
