name: Deploy Frontend to AWS S3

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          npm run export
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy to S3
        run: |
          aws s3 sync frontend/out s3://rant-zone-frontend --delete
          
      - name: Invalidate CloudFront cache
        run: |
          # Get CloudFront distribution ID (you'll need to add this as a secret)
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*" || echo "CloudFront invalidation skipped - distribution ID not set"
            
      - name: Deploy status
        run: |
          echo "✅ Frontend deployed successfully!"
          echo "🌐 S3 Bucket: rant-zone-frontend"
          echo "🔗 Website URL: http://rant-zone-frontend.s3-website-us-east-1.amazonaws.com" 